### ISSUE TITLE
OBSWebsocket blocks forever when OBS gets killed

### ISSUE THREAD

**Issue by Ben8823** [BarRaider/obs-websocket-dotnet#1]
If my application is connected to the websocket-server, and OBS gets killed the websocket does not get disconnected or something similar. If I'm doing another request the websocket blocks forever. A timeout for the websocket would fix the problem. Also a Disconnect event would be nice.

**Comment by Palakis** [comment]
Hi @Ben8823, I just implemented this in the library. Sorry for the long delay.
Added `Connected` and `Disconnected` events, and requests pending when a disconnect occurs are cancelled and throw a `ErrorResponseException`.

You can try the NuGet package of the latest changes (as of writing) here: https://ci.appveyor.com/api/buildjobs/au7kp4j8bbaml64l/artifacts/obs-websocket-dotnet.4.2.0-beta.nupkg
The test client has been updated as well.
