### ISSUE TITLE
[BUG] `OBSWebsocket` throws an exception a minute after an unsuccessful connection

### ISSUE THREAD

**Issue by DmitriySalnikov** [BarRaider/obs-websocket-dotnet#104]
**Issue Type** 
- Bug 

**Describe the bug**
It seems to me that after a failure, connection attempts should stop and the client should close.
(but on my side I implemented auto-reconnection..)

**To Reproduce**
1. Open TestClient
2. Press `Connect`
3. Wait a minute or so if OBS opened and few seconds if OBS closed.

**Expected behavior**
Nothing happens

**Screenshots**
![image](https://user-images.githubusercontent.com/7782218/188901554-3f9b098d-fb3b-4ca1-ac59-97943a2b5c59.png)

**Versions**
OBS Version: 28.0.1
OBS WebSocket Version:
OBS WebSocket Dotnet (this library) Version: 257e7b48e1c365fcf2ea3de9f156ded2bf8f5247
OS: Windows 11

**Comment by BarRaider** [comment]
Fixed by a3e0f5
