### ISSUE TITLE
[BUG] Both obs.GetVersion() and obs.GetDirectory() doesnt work with 5.0.0 nuget version

### ISSUE THREAD

**Issue by det-peralta** [BarRaider/obs-websocket-dotnet#109]
**Issue Type** 
- Bug 

**Describe the issue**
With the nuget version 5.0.0, both obs.GetVersion() and obs.GetRecordDirectory() doesnt work.
Can you update the nuget to 5.0.1 so the latest changes are applicable?

**To Reproduce**
1. Just call obs.GetVersion() or obs.GetRecordDirectory()

**Expected behavior**
OBS version and OBS Recording Path as string

**Versions**
OBS Version: 28.0.1
OBS WebSocket Version:  5.0.2
OBS WebSocket Dotnet (this library) Version: 5.0.0
OS:  Windows 11

**Comment by BarRaider** [comment]
We're in a bit of a refactor, finishing it up and releasing 5.0.1

**Comment by BarRaider** [comment]
Fixed in v5.0.1 release
