### ISSUE TITLE
StartReplayBuffer()/StartRecording() not working.

### ISSUE THREAD

**Issue by finnole12** [BarRaider/obs-websocket-dotnet#14]
Hey 
im not sure why but the StartReplayBuffer() and StartRecording() functions are not doing anything in my application. The IsConnected Event gets triggered though so i guess it is connected just fine.
Any Suggestions are apreciated.
attached is the whole code of my class. I use StartRecording in private static void setScene();

[OBS Supporter.txt](https://github.com/Palakis/obs-websocket-dotnet/files/3144513/OBS.Supporter.txt)

**Comment by BarRaider** [comment]
Closing this issue as it's over 1 year old. If issue still exists, please reopen
