### ISSUE TITLE
Program crashes with almost every single function.

### ISSUE THREAD

**Issue by JohnMackYouTube05** [BarRaider/obs-websocket-dotnet#19]
Every time I click on a button, which I programmed with help from your example program, so I know it should work, the program crashes and Visual Studio 2017 throws up this error: 
![image](https://user-images.githubusercontent.com/16242045/61565361-69b9f680-aa3e-11e9-867d-bba149910c7a.png)
It's very frustrating, can someone please tell me how to fix this?
The variable object shouldn't be null if the websocket class is supposed to grab that info from OBS when connected!

**Comment by jcalado** [comment]
It seems you missed actually connecting to your obs websocket server instance.

Try `obsws.Connect("ws://127.0.0.1:4444","password");`

Where 127.0.0.1:4444 is the ip:port to obs websocket server.

**Comment by JohnMackYouTube05** [comment]
Thank you, but where would I put that code? Do I have to reconnect to my OBS websocket instance every time I click a button?

**Comment by jcalado** [comment]
For now, just try to load it just after the program starts.
Inside your main function will do.
