### ISSUE TITLE
Update to API to match with updates to obs-websocket (Text GDI, etc)

### ISSUE THREAD

**Issue by SaviorXTanren** [BarRaider/obs-websocket-dotnet#2]
Hey, wanted to see what the plans for updating this API were in relation to your update to obs-websocket. I'd love to take advantage of the new APIs, such as the get & set Text GDI. Thanks!

**Comment by Palakis** [comment]
Thanks for the reminder. I'll take a look a this next week!

**Comment by Palakis** [comment]
I added most of the new request types to the library and pushed a beta release on NuGet. GDI+ Text and BrowserSource get/set aren't implemented yet.

**Comment by Palakis** [comment]
BrowserSource get/set added, as well as Connected/Disconnected events. New build available on NuGet.

GDI+ Text source properties are more complex to implement in this library, and I don't have much time to work on it. You can directly use the `SendRequest` method, which is used internally by other request calls, to manually call TextGDIPlus requests. Maybe you could contribute it to the library, if you feel so.

**Comment by TheDaChicken** [comment]
Can you also add ways to control the Media Sources Local File?

**Comment by mutilator** [comment]
I've added all current websocket functionality in this PR. Let me know if you run into any issues.
https://github.com/Palakis/obs-websocket-dotnet/pull/18
