### ISSUE TITLE
SetBrowserSourceProperties() no longer works with latest changes

### ISSUE THREAD

**Issue by SaviorXTanren** [BarRaider/obs-websocket-dotnet#22]
The following change was made back in June of last year to SetBrowserSourceProperties() by @mutilator:

https://github.com/Palakis/obs-websocket-dotnet/commit/acafac4dae62ce566d68bf6e067758a2adae1114#diff-f8dd625361d881e0de0a88a5612187caL694

Looking at the code, I'm not entirely sure what it's supposed to be doing now? The previous version actually assembled the JObject with the various properties. Now it just makes an empty JObject?

**Comment by SaviorXTanren** [comment]
For reference, here's what originally happened in the code:

`            var request = new JObject();
            request.Add("source", sourceName);
            if (sceneName != null)
                request.Add("scene-name", sourceName);

            request.Merge(props.ToJSON(), new JsonMergeSettings()
            {
                MergeArrayHandling = MergeArrayHandling.Union
            });

            SendRequest("SetBrowserSourceProperties", request);`

**Comment by SaviorXTanren** [comment]
I've added a pull request in with a fix for it for reference.

**Comment by mutilator** [comment]
Thanks, that appears to be my bad. It looks like I never finished the implementation!

**Comment by hellphish** [comment]
I have tested the change on @SaviorXTanren 's fork and found no issues.

**Comment by SaviorXTanren** [comment]
@hellphish Yep, just waiting on @Palakis or someone who has the authority to approve a pull request for the last few months.

**Comment by BarRaider** [comment]
Sorry for the delay.
I've recently received access to contribute to this repo. Pull request has been approved

**Comment by SaviorXTanren** [comment]
No problem, thanks for taking care of it!
