### ISSUE TITLE
SendRequest("ToggleStudioMode") crashes OBS (25.0.8. win x64)

### ISSUE THREAD

**Issue by sb-loup** [BarRaider/obs-websocket-dotnet#24]

**Comment by sb-loup** [comment]
same with: 
SetStudioMode(true);
EnableStudioMode();  (actually, don't know the difference between them)

and weird behaviour with:
SetStudioMode(false);
DisableStudioMode();

(WebSocket 4.7.0)

**Comment by tt2468** [comment]
Fixed in v4.8.0

**Comment by sb-loup** [comment]
great. work like a charm
