### ISSUE TITLE
SetRecordingFolder does not pass parameter

### ISSUE THREAD

**Issue by JashanChittesh** [BarRaider/obs-websocket-dotnet#3]
Sorry for not posting this as a Pull request but I'm in crunch mode for a demo. It's a super-simple fix in 

OBSWebsockets_Requests.cs - https://github.com/Palakis/obs-websocket-dotnet/blob/master/obs-websocket-dotnet/OBSWebsocket_Requests.cs

Current implementation: 

        public void SetRecordingFolder(string recFolder)
        {
            var requestFields = new JObject();
            requestFields.Add("rec-folder", recFolder);
            SendRequest("SetRecordingFolder");
        }

Correct implementation (simple add parameter "requestFields" to call to SendRequest):

        public void SetRecordingFolder(string recFolder)
        {
            var requestFields = new JObject();
            requestFields.Add("rec-folder", recFolder);
            SendRequest("SetRecordingFolder", requestFields);
        }

**Comment by Palakis** [comment]
...shit. Sorry.

**Comment by Palakis** [comment]
Fixed right now in https://github.com/Palakis/obs-websocket-dotnet/commit/8287569f8b625bd6a6ae40787472eceee85ed61a

**Comment by JashanChittesh** [comment]
Cool, thanks. No worries ... it did take a little to figure it out but with the error message and the code it was pretty obvious.

**Comment by moritzuehling** [comment]
Sorry to bug about this - but can you deploy that fix to NuGet as well?

I'm using this in a big-ish project and it would be awesome to be able to continue using the NuGet version and not go through the hassle of setting up a submodule and including it in our build-process.
