### ISSUE TITLE
SetRecordingFolder not updating

### ISSUE THREAD

**Issue by Spo-oky** [BarRaider/obs-websocket-dotnet#34]
Hi,

I'm using websock 4.8 and OBS 25.0.8 and I'm trying to use SetRecordingFolder like 

_obs.SetRecordingFolder("C:/TESTFOLDER/");
_obs.ToggleRecording();

In OBS the folder is not assumed and if I make a 

_obs.GetRecordingFolder();

It appears "C:/TESTFOLDER/" but in OBS still uses the default location and records to the default location.
Is there something missing?

Thanks.

**Comment by BarRaider** [comment]
Hi,
Any chance you were recording while calling this function?
As indicated in the docs:
_Please note: if SetRecordingFolder is called while a recording is in progress, the change won't be applied immediately and will be effective on the next recording._

https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#setrecordingfolder

**Comment by Spo-oky** [comment]
Hi,

Thanks for the fas reply. I found out what is the problem.

So in recording tab if you have chosen ffmpeg and not the normal output it not assume the recording folder, I've passed to default and worked.
So I think the problem is on the main obs websocket plugin and not on the c# lib...

Going to open a issue on obs websocket plugin.

Thanks.
