### ISSUE TITLE
SceneItemPositionInfo property typo

### ISSUE THREAD

**Issue by kennipj** [BarRaider/obs-websocket-dotnet#36]
https://github.com/Palakis/obs-websocket-dotnet/blob/9b778079e03600fbcae18fd68c8d77b588971dfa/obs-websocket-dotnet/Types/SceneItemPositionInfo.cs#L14

**Comment by BarRaider** [comment]
Fixed in latest commit 
https://github.com/Palakis/obs-websocket-dotnet/commit/d413292ee0afb15982ea5c0b1af4035977b0238e
