### ISSUE TITLE
changing source visibility

### ISSUE THREAD

**Issue by 1nexis** [BarRaider/obs-websocket-dotnet#37]
Is there a way for me to change the visibility of a Source?
I basically want to hide and unhide it to make it play a short video

**Comment by pjmagee** [comment]
`obs.SetSourceRender("SourceName", visible: false, sceneName: "SceneName");`

**Comment by tinodo** [comment]
You can also use SetSceneItemProperties;
`var props = new SceneItemProperties(){ItemName = "SourceName", Visible = false};
obs.SetSceneItemProperties(props, "SceneName");`
