### ISSUE TITLE
Problem with .NET Core 3.1.0

### ISSUE THREAD

**Issue by lucalas** [BarRaider/obs-websocket-dotnet#41]
Hi,
when I call .Connect method i receive this error:

System.IO.FileNotFoundException: 'Could not load file or assembly 'websocket-sharp, Version=1.0.2.59611, Culture=neutral, PublicKeyToken=5660b08a1845a91e'. 

I think that is due to .NET Core 3.1 application that i'm creating.
when do you think to release a new version with .NET Core compatibility?

**Comment by BarRaider** [comment]
Use .Net Core 3.0
No timeline for 3.1 support
