### ISSUE TITLE
Feature Request: Support sending Hotkeys using the library.

### ISSUE THREAD

**Issue by tinodo** [BarRaider/obs-websocket-dotnet#44]
Websockets just got update with an important feature; the ability to send Hotkeys to OBS Studio.

More information here: [https://github.com/Palakis/obs-websocket/pull/595](https://github.com/Palakis/obs-websocket/pull/595)

Can these 2 methods be implemented in the library (after websocket 4.10 is released)?

Thanks!

**Comment by BarRaider** [comment]
Currently it's still in a dev branch, can add it as soon as obs-websocket releases a new version (4.9)

**Comment by tinodo** [comment]
obs-websocket v4.9.0 has been release which includes these methods.
I have implement them, and a few others; https://github.com/BarRaider/obs-websocket-dotnet/pull/50
