### ISSUE TITLE
GetBrowserSourceProperties() - System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by SaviorXTanren** [BarRaider/obs-websocket-dotnet#5]
Hey, I've noticed that at certain times when trying to call GetBrowserSourceProperties(), I get an exception back failing at the following line:

https://github.com/Palakis/obs-websocket-dotnet/blob/master/obs-websocket-dotnet/OBSWebsocket_Requests.cs#L685

System.ArgumentNullException: Value cannot be null.
Parameter name: value
at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
at OBSWebsocketDotNet.BrowserSourceProperties..ctor(JObject props)
at OBSWebsocketDotNet.OBSWebsocket.GetBrowserSourceProperties(String sourceName, String sceneName)
at MixItUp.OBS.OBSService.SetWebBrowserSource(String source, String url) in C:\GitHub\mixer-mixitup\MixItUp.Desktop\Services\OBSService.cs:line 81

Not any other info, seems to be semi-random when it happens, but then happens continuously when it starts happening.

**Comment by SaviorXTanren** [comment]
Found out more about this. Here is the line of code in question that it is failing on:

Types.cs:625
             FPS = (int)props["fps"];

The value "fps" doesn't exist in the JObject that's returned back. Changing the code to something like the following removed the error:

            JToken fpsToken;
            props.TryGetValue("fps", out fpsToken);
            FPS = (fpsToken != null) ? (int)fpsToken : 0;

The above isn't a recommended fix, this a stop-gap for the time being.

**Comment by BarRaider** [comment]
GetBrowserSourceProperties has recently been updated. 
Closing this old issue, please reopen if happens again
