### ISSUE TITLE
Media Control

### ISSUE THREAD

**Issue by JMeyerEngineering** [BarRaider/obs-websocket-dotnet#55]
- Support Issue
How do I restart, play, and pause a media source such as VLC.?
I see there is a function "obs.sendrequest(string request,[Newtonsoft.Json.Linq.JObject additionalFields = null]) but I think I am overlooking the documentation on how it can be used and how the request should be formatted. Thanks ahead of time!

OBS Version:  26.1.1 (64 bit)
OBS WebSocket Version:  4.9
OBS WebSocket Dotnet (this library) Version:  obs-websocket-dotnet.4.8.1
OS:  Windows 10

**Comment by BarRaider** [comment]
See the obs-websocket documentation

https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#media-control
