### ISSUE TITLE
[BUG] ListScenes() crash/disconnect when called while OBS Filters window is open

### ISSUE THREAD

**Issue by Etuldan** [BarRaider/obs-websocket-dotnet#57]
**Issue Type** 
Bug 

**Describe the bug**
A call to ListScenes() (or SendRequest("GetSceneList") ) seems to crash and disconnect the socket, if it was done while the OBS windows Filters properties is open

**To Reproduce**
1. Create a OBSWebsocket with event "SourceFilterAdded" catched.
2. On the Event, call ListScenes()
3. Build, start, connect to OBS.
4. On OBS, for any source, add a new filter.
5. The OBSWebsocket object will crash/disconnect.

```c#
OBSWebsocket obs = new OBSWebsocket();
obs.SourceFilterAdded += Obs_SourceFilterAdded;

private void Obs_SourceFilterAdded(OBSWebsocket sender, string sourceName, string filterName, string filterType, JObject _filterSettings)
{
    List<OBSScene> scenes = obs.ListScenes();
}
```

**Expected behavior**
No crash, and a return of all Scene Objects

**Versions**
OBS Version: 26.1.1 (64 bit)
OBS WebSocket Version: 4.9.0
OBS WebSocket Dotnet (this library) Version: 4.9.0 (from NuGet)
OS: Windows 10 64 bit

**Comment by BarRaider** [comment]
You are causing a thread deadlock by running additional OBS commands from the event's calling thread.
You can envelope the ListScenes() in a Task.Run to invoke it in a proper thread
