### ISSUE TITLE
Dictionary (_responseHandlers) isn't thread safe

### ISSUE THREAD

**Issue by marksmeltzer** [BarRaider/obs-websocket-dotnet#6]
The web socket library you're using doesn't guarantee that callbacks are issued on the UI thread, or the current synchronization context, and as such, the incoming events are executing on random threads.

The fix would be to either wrap all access to _responseHandlers in a lock() statement (e.g. lock( _responseHandlers) {...})  or to modify _responseHandlers to be a ConcurrentDictionary instead of a Dictionary.

**Comment by pschichtel** [comment]
The proper solution would probably be to go full async in this case. Is there a reason the requests have to be sync?

**Comment by marksmeltzer** [comment]
Async or sync, wouldn't affect the issue I raised: the dictionary isn't thread safe.

Either (1) switch to a thread-safe dictionary like ConcurrentDictionary, or (2) use lock() to synchronize access to the dictionary to enforce thread-safety.

Regards,

On Apr 18, 2018 11:52 PM, Phillip Schichtel <notifications@github.com> wrote:

The proper solution would probably be to go full async in this case. Is there a reason the requests have to be sync?

**Comment by pschichtel** [comment]
Well it wont make the Dictionary magically thread-safe, that is true. However it will make the Dictionary unnecessary from what I have seen.
