### ISSUE TITLE
System.ArgumentOutOfRangeException: "Zero or less. "

### ISSUE THREAD

**Issue by AndreR** [BarRaider/obs-websocket-dotnet#60]
Here's my minimal example:

```c#
using OBS.WebSockets.Core;
using System;
using System.Windows.Forms;

namespace OBS_Controller
{
    public partial class Form1 : Form
    {
        protected OBSWebsocket OBS;

        public Form1()
        {
            InitializeComponent();

            OBS = new OBSWebsocket();

            try
            {
                OBS.Connect("ws://localhost:4444", "MyPassword");
            }
            catch (Exception)
            {
                // ERROR
                throw;
            }
            
            label1.Text = OBS.IsConnected.ToString();
        }

    }
}
```

This throws me the following error: _System.ArgumentOutOfRangeException: "Zero or less. "_ What's wrong with my code?

**Comment by AndreR** [comment]
I found a solution: It seems to be required to set `WSTimeout` to a value manually. Default is 0 seconds.

**Comment by BarRaider** [comment]
Thanks for reporting!
I will check the feasibility of adding a default non-zero value

**Comment by BarRaider** [comment]
Was not able to reproduce this issue. On further inspection of the code, there is a default 10 seconds timeout already in the code.
