### ISSUE TITLE
[BUG] TransitionToProgram throws Json error

### ISSUE THREAD

**Issue by LukasLichten** [BarRaider/obs-websocket-dotnet#62]
**Issue Type** 
- Bug 

**Describe the bug**
Whenever Passing any transition value other then -1 you get a "Can not add Newtonsoft.Json.Linq.JValue to Newtonsoft.Json.Linq.JObject"

**Versions**
OBS Version: 27.0.1
OBS WebSocket Version: 4.9.1
OBS WebSocket Dotnet (this library) Version: 4.9.0
OS: Windows 10

**Solution**
OBSWebsocket_Requests.cs
ln 1140
only the duration key is added, the transitionDuration is not, making it a JValue Object that crashes on that line

**Comment by BarRaider** [comment]
Fixed in dev-4.9.1 branch, will be merged in next release.

**Comment by BarRaider** [comment]
Resolved in 4.9.1-Beta1 release
