### ISSUE TITLE
Feature Request: Gamecapture

### ISSUE THREAD

**Issue by WoweePaw** [BarRaider/obs-websocket-dotnet#7]
Would be great to have access to it (if you have time for it to add) :)

Oh and thanks for your great work on this. 👍

**Comment by Palakis** [comment]
@D3thw0lf what do you mean by Gamecapture ? even obs-websocket doesn't have the feature to grab screenshots yet.

**Comment by WoweePaw** [comment]
No no I don't mean screenshots. I mean the Game Capture in OBS (like on the Screenshot). 
![gamecapture](https://user-images.githubusercontent.com/895448/38817530-d9db6d32-4198-11e8-988a-4490b2055d55.jpg)

I'm very new to this OBS & Websocket Stuff and I would love to change the selected Window (the red one on the screenshot) to capture (for example) if this is possible.

**Comment by BarRaider** [comment]
Closing all 4.9.x issues, if still happens on v5 please reopen
