### ISSUE TITLE
[ISSUE]When clicking on Events in Advanced on Visual Studio example

### ISSUE THREAD

**Issue by mccla5214** [BarRaider/obs-websocket-dotnet#76]
**Issue Type** No Response to event

# Only keep ONE of the options below:

- Support Issue

**Describe the issue**

When I click on events in advanced dialog, nothing happens. Traced code through with debug and Events code is executing without errors but nothing is displayed in the box to the left. I may just not understand what is supposed to happen.

1. Go to '...' Advanced
2. Click on '....' Events

**Expected behavior**

Expected events in OBS like start stop streaming to show

**Screenshots**

**Versions**
OBS Version: 27.0.1
OBS WebSocket Version:4.9.1
OBS WebSocket Dotnet (this library) Version: Running the latest binary download from this site on Visual Studio 2019
OS: [e.g. Windows 10] Windows 10

**Additional context**

**Comment by BarRaider** [comment]
Are you talking about the test client?

**Comment by mccla5214** [comment]
Yes. Also on the CPU stats, my task manager is saying 27% and the stat for
cpu is 17%, is the cpu supposed to be the gpu

Mike

**Comment by BarRaider** [comment]
The test client is just that, one for testing. There is no expectation for all events or features to be covered.
You are welcome to add more features and PR them.

Regarding the CPU, the data is supplied by OBS itself so it's whatever OBS says is the usage
