### ISSUE TITLE
Using SendRequest for 4.3 SetSceneItemProperties

### ISSUE THREAD

**Issue by Fantmx** [BarRaider/obs-websocket-dotnet#8]
First, thanks a bunch for putting this on dotnet. I know it appears that this version will not be upgraded to 4.3 and unfortunately what I am trying to accomplish is in 4.3. 

I have been trying to use Set and GetSceneItemProperties with the SendRequest() method however I am always getting an error:

> WebSocket.message|System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

If you have a moment could you help me understand how to pass the correct information to SendRequest() or tell me if this method would even work still. I have a feeling I am passing the wrong information.

Here is the code: 

`JObject item = new JObject();
item.Add("message-id", "1234");
item.Add("scene", "Intro");
item.Add("Item.name", "Color");
item.Add("Item.visible", false);
var response = _obs.SendRequest("SetSceneItemProperties", item);`

Thank you for any help in this!

**Comment by Palakis** [comment]
hi @Fantmx, thanks for your interest in this!
Yeah, I acknowledge that this lib is lagging behind obs-websocket features... and bugfixes as well. It will be updated to 4.3, but I don't know when I can do this. Do you think you could contribute that fix?

**Comment by Fantmx** [comment]
I can look at adding to the lib. I am very new to coding however just to be warned. That being said I know enough to clone and add newer methods for 4.3 not currently in the library.

**Comment by BarRaider** [comment]
Closing this old issue, please reopen if happens again
