### ISSUE TITLE
Is the support for netframework removed?

### ISSUE THREAD

**Issue by Groboto** [BarRaider/obs-websocket-dotnet#80]
After version 4.0 there is no way to compile for netframework?
Can explain if netframework support is removed?

I can select netframework up to 4.8 without problems without problem, but staring with obs-websocket-dotnet-4.8.1 there is no way to doit.
There is something im doing wrong?

**Comment by BarRaider** [comment]
Definitely supported.
It's using .Net Standard
Just use nuget to get the version
Otherwise you'll need to compile it yourself

**Comment by Groboto** [comment]
Thanks for your fast reply, really appreciated.

I downloaded source code  obs-websocket-dotnet-4.9.1
There is no way to compile for netframework, when i select on visual studio properties, I only can select .net standard 2.0 for the library.
For the test client, only can select netcore 3.0 3,3 and 5.0

On sourcecode obs-websocket-dotnet-4.8  I can select netframework without problem for the library (obs-websocket-dotnet) and for the demo example  (TestClient) 
Now cant.

**Comment by BarRaider** [comment]
Let's take a step back, what are you trying to do?
Why would you need to COMPILE it for .net framework

**Comment by Groboto** [comment]
Thanks so much for your time.
All my project is developed under net Framework 4.8, and plan do usage of your greta lib, there is no needed for me to move to .net Core or any new technology duet I have all what I need on .net Framework 4.8 WPF, that is the reason.
As I said before all is ok up to obs-websocket-dotnet-4.8  after that.....cant compile for net Framework.

Apologize my non perfect english.

**Comment by BarRaider** [comment]
Libraries compiled on .Net Standard are supported on .Net framework too. Why are you trying to compile instead of just using nuget or using the dll from the release

**Comment by Groboto** [comment]
Just beacsuse I not use nuget, and just downloaded the test example source also for compile , test and learn.
Basically I understand can then compile the library using .net standard 2.0 and that works with netframework 4.8, ok no problem.
And the demo test, how can compile under netramework 4.8?

**Comment by BarRaider** [comment]
You can create a new .net framework project and move all the files there.
The test client is a winforms one iirc.

I'm closing this issue as there isn't really an issue. It's supported on .Net Framework but what you want is for educational purposes just to compile it specifically with .Net framework and for that you can create a new project.
