### ISSUE TITLE
[BUG] 'System.PlatformNotSupportedException' When Trying To Connect()

### ISSUE THREAD

**Issue by pbuchi2000-adiacom** [BarRaider/obs-websocket-dotnet#89]
**Issue Type** 
- Bug 

**Describe the bug**
Getting 'System.PlatformNotSupportedException' when trying to run obs.Connect(serverIp, serverPassword).

The output is:
Exception thrown: 'System.PlatformNotSupportedException' in websocket-sharp.dll
An unhandled exception of type 'System.PlatformNotSupportedException' occurred in websocket-sharp.dll
Operation is not supported on this platform.

VS says the command causing the exception is:
WSConnection.Connect();

Same result with both obs-websocket-dotnet project and NuGet package

Target framework is currently .NET 6.0 but the error is the same when trying older .NET Core 3.0

**To Reproduce**
1. Follow TestClient demo
2. Exception happens when trying connect()

**Expected behavior**
Should connect & proceed with the later steps of the demo project

**Screenshots**

**Versions**
OBS Version: 27.2.4
OBS WebSocket Version: 5.0.0-beta1
OBS WebSocket Dotnet (this library) Version: 4.9.1
OS: Windows 10 Pro

**Additional context**

![OBS DotNet Exception](https://user-images.githubusercontent.com/79928749/161720858-4e496e86-598c-4495-99c5-6d98ed3edc43.jpg)

**Comment by BarRaider** [comment]
Issue seems to be related to a bug in the dependent Websocket.
See workaround here: 
https://github.com/sta/websocket-sharp/issues/601

**Comment by pbuchi2000-adiacom** [comment]
Thanks for the quick response. You've saved me a lot of reading & head scratching :-)

**Comment by pbuchi2000-adiacom** [comment]
That workaround isn't applicable. It says:
"I use connectasync() to connect to server,it throws the same error, but it works fine when I use connect"
but your code already uses connect()

![OBS DotNet Exception 2](https://user-images.githubusercontent.com/79928749/161741350-c57e1a2d-c9f4-4ba3-9e07-bd959414c272.jpg)

**Comment by Ashish-jangir** [comment]
Did you find any solution. I am getting the same issue with .NET 6.0
