### ISSUE TITLE
SetSourceSettings

### ISSUE THREAD

**Issue by AndreZila01** [BarRaider/obs-websocket-dotnet#90]
**Issue Type** 
# Only keep ONE of the options below:
- Support Issue

**Describe the issue**

I would like set url on Media Player ... at the moment i have this 
`obs.SetSourceSettings("Oshawott", JsonConvert.DeserializeObject<dynamic>("[{\"local_file\": \"C:/Users/bot/Documents/GitHub/Twitch/Bot/Bot/Resources/Oshawott1.mp4\"}]"));`

![First message error](https://user-images.githubusercontent.com/56931353/172049550-9df58d0e-35f7-40a9-ad2c-b30de050fa29.png)

![second message error](https://user-images.githubusercontent.com/56931353/172049544-fe14e426-01c9-4d63-9ae9-4732538578f8.png)

**Versions**
OBS Version:  27.2..4
OBS WebSocket Version: 4.9.1
OBS WebSocket Dotnet (this library) Version: i dont know
OS: Windows 10

**Comment by BarRaider** [comment]
Closing all 4.9.x issues, if still happens on v5 please reopen
