### ISSUE TITLE
Failure to handle lack of virtual camera

### ISSUE THREAD

**Issue by mj2015** [BarRaider/obs-websocket-dotnet#98]
**Issue Type** 
- Bug 

**Describe the bug**
If the library is used to connect to a Linux OBS, the virtual camera status will throw an exception.

**To Reproduce**
1. Run the test software
2. Connect to an Ubuntu install of OBS 28.0.1
3. Exception occurs

The error content from OBS is: `"requestStatus": {
  "code": 604,
  "comment": "VirtualCam is not available.",
  "result": false
}`

**Expected behavior**
This should not cause an exception given it is checking status.

My code to "fix" this is:

        /// <summary>
        /// Gets the status of the virtualcam output.
        /// </summary>
        /// <returns>An <see cref="VirtualCamStatus"/> object describing the current virtual camera state</returns>
        public VirtualCamStatus GetVirtualCamStatus()
        {
            try
            {
                JObject response = SendRequest(nameof(GetVirtualCamStatus));
                var outputStatus = new VirtualCamStatus(response);
                return outputStatus;
            }
            catch (Exception)
            {
                return new VirtualCamStatus() { IsActive = false };
            }
        }

It may be better to add a specific exception, and perhaps have an additional property to indicate "present" or not.

**Versions**
OBS Version: 28.0.1 Ubuntu
OBS WebSocket Version: Built in
OBS WebSocket Dotnet (this library) Version: latest from 5 mins ago
OS: [e.g. Windows 10] Windows 10

**Comment by BarRaider** [comment]
This is a server error from the OBS Websocket. You should probably put the try/catch in your code, as none of the requests have try/catch by design. This is intended so that any errors are properly propagated to the consumer.
